version: '3.7'
services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  mysql8:
    image: mysql:8
    ports:
      - "3306:3306"
    restart: always
    networks:
      - monorepo
    environment:
      MYSQL_DATABASE: db_monorepo
      MYSQL_ROOT_PASSWORD: sasa
  postgres12:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    restart: always
    networks:
      - monorepo
    environment:
      POSTGRES_DB: db_monorepo
      POSTGRES_PASSWORD: sasa
networks:
  monorepo: